import { Tierra } from "./tierra";

export const TIERRA:Tierra []=[
    {
        nombre: "Aguasturbias",
        bio: "Situada en la lejanía, en el archipiélago de las Islas de la Llama Azul, Aguasturbias es una ciudad portuaria como ninguna otra: hogar de cazadores de serpientes, pandillas de muelle y contrabandistas de todo el mundo conocido. En este lugar se hacen fortunas y las ambiciones se destruyen en un abrir y cerrar de ojos. Para aquellos que huyen de la justicia, de las deudas o de los persecutores, Aguasturbias puede ser un lugar de nuevos comienzos, ya que en estas calles retorcidas a nadie le interesa tu pasado. Pese a ello, en cada nuevo amanecer, siempre se pueden encontrar viajeros imprudentes flotando en el puerto, con las bolsas vacías y la garganta cortada... Si bien puede ser extremadamente peligrosa, en Aguasturbias abundan las oportunidades exentas de las ataduras de un gobierno oficial y de un reglamento del comercio. Si tienes el dinero, puedes comprar casi cualquier cosa: desde Hextech ilegal hasta los servicios de los criminales locales. Con el reciente derrocamiento del último ''rey saqueador'' de Aguasturbias, la ciudad atraviesa un periodo de transición en el que los capitanes más prominentes tratan de llegar a un acuerdo para definir su futuro. No obstante, mientras haya embarcaciones en buen estado y tripulaciones dispuestas a navegar en ellas, es probable que siga siendo uno de los lugares más coloridos y mejor conectados en Runaterra.",
        img: "assets/img/aguasturbias.jpg",
      },
      {
        nombre: "Demacia",
        bio: "Al pertenecer a un reino poderoso y aferrado a la ley con una prestigiosa historia militar, los habitantes de Demacia valoran ante todo los ideales de justicia, de honor y del deber, al tiempo que se enorgullecen acérrimamente de su herencia cultural. Pero, a pesar de sus principios nobles, esta gran nación autónoma se ha vuelto cada vez más insular y aislacionista durante los últimos siglos. Ahora, Demacia es un reino sumido en el caos. Su capital, la gran ciudad de Demacia, fue fundada como un refugio frente a la hechicería tras la pesadilla de las Guerras Rúnicas, y construida a partir del enigma de la petricita, una peculiar roca blanca que disminuye la energía mágica. Es desde aquí que la familia real ha velado por la defensa de las aldeas y pueblos cercanos, las tierras de cultivo, los bosques y las montañas ricas en recursos minerales. No obstante, tras la repentina muerte del rey Jarvan III, el resto de las familias nobles no ha aprobado aún la sucesión al trono de su único heredero, el joven príncipe Jarvan. Quienes viven más allá de las fronteras sumamente resguardadas son vistos cada vez más con sospecha, mientras que varios antiguos aliados comenzaron a recurrir a otros en busca de protección en medio de estos tiempos inciertos. Algunos se atreven a murmurar que la edad de oro de Demacia ya pasó y, a menos que sus habitantes estén dispuestos a adaptarse al mundo cambiante (algo de lo que algunos no se creen capaces), el declive del reino parece inevitable. Ni toda la petricita en su territorio podrá proteger a Demacia de sí misma.",
        img: "assets/img/demacia.jpg",
      },
      {
        nombre: "Freljord",
        bio: "El Fréljord es un lugar duro y despiadado en donde sus habitantes nacen siendo guerreros y tendrán que prosperar contra todo pronóstico. Orgullosas y poseedoras de una independencia feroz, las tribus del Fréljord son consideradas salvajes, ásperas y ''bárbaras'' por sus vecinos a lo largo de Valoran, quienes desconocen las tradiciones antiguas que las forjaron. Varios miles de años atrás, la alianza entre las hermanas Avarosa, Serylda y Lissandra se quebró en una guerra que, sin saberlo, amenazó a toda Runaterra al sumir en caos y en un invierno casi permanente a las tierras del norte. Ahora, solo aquellos mortales verdaderamente excepcionales, inmunes a los estragos del fuego y del viento, son quienes aparentan estar destinados a liderar. A pesar de los grandes esfuerzos de la Guardia de Hielo, aún perduran los mitos y las leyendas de los dioses antiguos, los yetis enigmáticos y los chamanes cambiapieles. Los invasores de la Garra Invernal abarcan más territorios con cada año que pasa, hostigando las fronteras de Demacia al sur y las de Noxus al este. Por su parte, algunas tribus y clanes desobedientes e independientes que buscan un futuro más pacífico han comenzado a aliarse con Ashe, la joven reina de los avarosanos. A pesar de ello, los presagios son desalentadores. Sin lugar a dudas, la guerra regresará al Fréljord y nadie podrá escapar.",
        img: "assets/img/freljord.jpg",
      },
      {
        nombre: "El Vacio",
        bio: "Comenzando a gritos su existencia junto al nacimiento del universo, el Vacío es una manifestación de la nada inasible que se encuentra más allá. Es una fuerza con un hambre insaciable, esperando a través de los eones hasta que sus amos, los misteriosos Vigilantes, marquen la hora final. Ser un mortal tocado por este poder significa sufrir un atisbo agonizante de eterna irrealidad, suficiente como para quebrar hasta la mente más fuerte. Los habitantes del Vacío son criaturas construidas, usualmente con una conciencia limitada, pero programadas con un propósito singular: desatar el olvido total por toda Runaterra.",
        img: "assets/img/vacio.png",
      },
      {
        nombre: "Jonia",
        bio: "Rodeada por mares traicioneros, Jonia se compone de una serie de provincias aliadas repartidas por un gran archipiélago conocido por muchos como las Tierras Originarias. La búsqueda del equilibrio entre todas las cosas es lo que ha moldeado a la cultura jonia, por lo que el límite entre los reinos de lo material y lo espiritual suele ser más permeable ahí, en especial en los bosques silvestres y en las montañas. Si bien los encantos de estas tierras pueden ser veleidosos, dada la naturaleza peligrosa y mágica de su fauna, la mayor parte de los jonios tuvo una vida próspera durante varios siglos. Los monasterios de los guerreros, las milicias provinciales e incluso Jonia misma habían bastado para protegerlos. Pero eso terminó hace doce años, cuando Noxus atacó las Tierras Originarias. Las aparentemente infinitas huestes del imperio arrasaron con Jonia y tuvieron que pasar muchos años para que cayeran derrotadas, a un costo muy alto. Ahora, Jonia existe en una paz inquieta. Las diferentes reacciones frente a la guerra dividieron la región. Algunos grupos, como los monjes Shojin o los Kinkou, buscan volver a la paz que conlleva el aislamiento y a las tradiciones pastoriles. Otras facciones más radicales, como la Hermandad Navori y la Orden de la Sombra, exigen la militarización de la magia de la tierra para crear una nación unificada que pueda vengarse de Noxus. El destino de Jonia pende de un delicado equilibrio que muy pocos están dispuestos a alterar, pero que todos pueden sentir cómo se mueve inquietamente bajo sus pies.",
        img: "assets/img/jonia.jpg",
      },
      {
        nombre: "Noxus",
        bio: "Noxus es un imperio poderoso con una reputación aterradora. Para quienes viven más allá de sus fronteras, es brutal, expansionista y amenazante. Sin embargo, para aquellos que logran ver más allá de su exterior bélico, se encuentran con una sociedad inusualmente inclusiva que respeta y cultiva las fortalezas y los talentos de los suyos. Los Noxii fueron en el pasado feroces tribus barbáricas hasta que invadieron la antigua ciudad que ahora se encuentra en el corazón de su dominio. Amenazados por todos los flancos, pelearon encarnizadamente contra sus enemigos y expandieron sus fronteras año tras año. Esta lucha por la supervivencia moldeó la identidad de los noxianos modernos: gente profundamente orgullosa que valora la fuerza sobre todas las cosas, aunque esta puede manifestarse de diferentes maneras. Cualquiera puede ascender a una posición de poder y respeto en Noxus si presenta la aptitud necesaria, más allá de su estrato social, antecedentes o riqueza. Aquellos que son capaces de ejercer la magia son tenidos en alta estima y son buscados con ahínco, con la intención de perfeccionar y aprovechar sus talentos al máximo en beneficio del imperio. A pesar de este ideal meritocrático, las antiguas familias nobles aún ostentan un poder considerable y algunos temen que la mayor amenaza para Noxus no provenga de sus enemigos, sino desde dentro.",
        img: "assets/img/noxus.jpg",
      },
      {
        nombre: "Piltover",
        bio: "Piltóver es una ciudad próspera y progresista cuyo poder e influencia van en ascenso. Es el centro cultural de Valoran, donde el arte, la producción artesanal, el comercio y la innovación van de la mano. Su poder no viene del poder militar, sino de los motores del comercio y las ideas avanzadas. Ubicada en los acantilados sobre el distrito de Zaun y con vista al océano, flotas de barcos pasan por sus titánicas compuertas con artículos de todas partes del mundo. La riqueza que esto genera ha dado lugar a un crecimiento de la ciudad sin prececedentes. Piltóver se ha reinventado como una ciudad donde se pueden amasar enormes fortunas y hacer realidad los sueños. Pujantes clanes de mercaderes pudieron desarrollarse en las actividades más increíbles: imponentes disparates artísticos, arcanas investigaciones sobre hextech y monumentos arquitectónicos enalteciendo su poder. Con una creciente cantidad de inventores en el emergente conocimiento de hextech, Piltóver se convirtió en un imán para los artesanos más habilidosos del mundo.",
        img: "assets/img/piltover.jpg",
      },
      {
        nombre: "Shurima",
        bio: "El imperio de Shurima fue alguna vez una civilización floreciente que abarcó un continente entero. Forjada, en una era ya olvidada, por los poderosos dioses guerreros de los Huéspedes Ascendidos, unificó a todos los pueblos discrepantes del sur e impuso una paz duradera entre ellos. Pocos se atrevían a rebelarse. Y quienes lo hicieron, como la condenada nación de Icathia, fueron aplastados sin piedad. Sin embargo, después de varios miles de años de crecimiento y prosperidad, la ascensión fallida del último emperador shurimano redujo la capital a ruinas y las historias de la antigua gloria del imperio se convirtieron en mitos. Ahora, la mayor parte de los habitantes nómadas de los desiertos de Shurima trata de sostener su endeble existencia valiéndose de la tierra despiadada. Algunos construyeron pequeños puestos de avanzada para defender los pocos oasis disponibles, mientras que otros hurgan en catacumbas desaparecidas hace mucho tiempo, en busca de las incontables riquezas que, seguramente, yacen enterradas ahí. También están aquellos que viven como mercenarios, quienes cobran por sus servicios antes de desaparecer en los páramos sin ley. Pese a ello, unos cuantos se atreven a soñar con el retorno de las viejas costumbres. De hecho, recientemente las tribus fueron alertadas por los susurros del corazón del desierto, los cuales afirman que el emperador Azir ha vuelto para guiarlos en una era nueva y maravillosa.",
        img: "assets/img/shurima.jpg",
      },
      {
        nombre: "Targon",
        bio: "El Monte Targón es la cima más poderosa de Runaterra, una montaña imponente de roca calcinada por el sol en medio de una cordillera de cumbres de escala incomparable en el mundo. El Monte Targón, ubicado lejos de la civilización, es totalmente remoto y su cúspide casi imposible, excepto para el explorador más resuelto. Como todo lugar mitológico, el Monte Targón es faro de soñadores, locos y aventureros. Algunos de estos valientes intentan escalar la montaña inalcanzable, tal vez en busca de sabiduría o iluminación, o por perseguir la gloria o quizá motivados por un anhelo profundo de pisar su cumbre. El ascenso es prácticamente irrealizable, y aquellos pocos que de alguna manera logran sobrevivir para llegar a su cima, casi nunca hablan de lo que vieron. Algunos vuelven con una mirada poseída y vacía, otros cambiados al punto de ser irreconocibles, imbuidos por un Aspecto de poder inhumano y sobrenatural, con un destino que pocos mortales comprenderían.",
        img: "assets/img/targon.jpg",
      },
      {
        nombre: "Zaun",
        bio: "Zaun es un gran distrito suburbano ubicado en la profundidad de los cañones y valles que rodean Piltóver. La poca luz que llega allí abajo se filtra por los vapores que salen de las tuberías corroídas y se refleja a través de los vitrales de la arquitectura industrial. Zaun y Piltóver estuvieron alguna vez unidas; ahora son sociedades separadas, pero simbióticas. A pesar de existir sumida en una permanente luz crepuscular, Zaun progresa, su gente es enérgica y su cultura es rica. La riqueza de Piltóver le permitió a Zaun desarrollarse a la par; un espejo oscuro de la ciudad de arriba. Muchos de los artículos que ingresan a Piltóver encuentran la manera de entrar al mercado negro de Zaun, al igual que las peligrosas investigaciones de los inventores hextech, que se topan con demasiadas restricciones en la ciudad encumbrada, muchas veces son bien recibidas en Zaun. El ilimitado desarrollo de tecnologías volátiles e industrias imprudentes corrompieron y pervirtieron grandes áreas de Zaun. Cantidades de desperdicios tóxicos quedan estancados en las partes más bajas de la ciudad, pero aún allí la gente encuentra la manera de existir y prosperar.",
        img: "assets/img/zaun.jpg",
      }
];